[package]
name = "leptos_chart"
version = { workspace = true }
edition = "2021"
authors = ["LangPham"]
license = "MIT"
repository = "https://github.com/theta-vn/leptos_chart"
description = "Chart library for leptos"
readme = "../README.md"

[dependencies]
leptos = {version = "0.3.0",  default-features = false, optional = true}
theta-chart = {path = "../../theta-chart", version = "0.0.3"}
log = "0.4.6"
wasm-logger = "0.2.0"

# [patch.crates-io]
# theta-chart = {path = "../../theta-chart", version = "0.0.3"}

[features]
default = ["csr", "stable"]
core = []
Axes = []
PieChart = ["core"]
BarChart = ["core", "Axes"]
LineChart = ["core", "Axes"]

csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
stable = ["leptos/stable"]
